### PR TITLE
Reset keySizes and keyValues GaugeVec before scraping to remove old data

### LINKED ISSUE #100: Returns last metric value (check-keys) if key is deleted from redis
I have started redis exporter with option to watch several keys (check-keys option). These keys are present  and deleted from time to time. I have found that redis exporter continue to return last registered metric value, if that key is not found in redis. 

For example, curling on /metrics endpoint 
`curl 127.0.0.1:9121/metrics | grep redis_key`
```
redis_key_size{addr="127.0.0.1:6379",alias="",db="db0",key="pikaspy.redis_utils.proxies.TargetsProcessingHash"} 1
redis_key_size{addr="127.0.0.1:6379",alias="",db="db0",key="pikaspy.redis_utils.proxies.UrlsList"} 5
redis_key_size{addr="127.0.0.1:6379",alias="",db="db0",key="pikaspy.redis_utils.proxies.UrlsProcessingHash"} 11
```
And watching these keys in redis:
```
127.0.0.1:6379> KEYS pikaspy.redis_utils.proxies.*
1) "pikaspy.redis_utils.proxies.TargetsProcessingHash"
```
The keys `pikaspy.redis_utils.proxies.UrlsList` and `pikaspy.redis_utils.proxies.UrlsProcessingHash` are absent but still returned by redis exporter.

P.S. Congrats on 100th issue!

UPD: Restarting exporter cleares its memory and it reports actual keys and data. until they deleted, of course.

### PR DESCRIPTION
**Pull request by sashgorokhov**
Closes #100

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks, this looks good!

Do you think you could add a test for this scenario?

**Comment by sashgorokhov** [comment]
I have a little experience with golang, but i will try!

**Comment by oliver006** [comment]
Thanks!

**Comment by oliver006** [comment]
(if you tested this locally/manually then I'm fine to go ahead and merge it but it'd be nice to have a test case for this)

fyi, you can try taking this test as a blueprint:

https://github.com/oliver006/redis_exporter/blob/master/exporter/redis_test.go#L380

to test your fix you'd need to do whatever the test above does and then delete one of the keys and scrape metrics again and see that the value of the deleted key is gone. Hope that helps.

**Comment by sashgorokhov** [comment]
@oliver006 please check circleci, all tests are failing because they cant reach redis instance.

**Comment by oliver006** [comment]
Hmm, I kicked of a rebuild of your PR and it ran the tests just fine, must have been a glitch with the redis process. However, the test for `go fmt` failed so try formatting your code and push up another commit.

**Comment by oliver006** [comment]
Thanks!

**Pull request merged**
