### PR TITLE
Add condition to check if key is of type string before running GET to increase performance

### PR DESCRIPTION
**Pull request by kerossin**
This adds a condition so that GET is only ran on types of keys that it works on - strings.

Before it was ran on every key and you could see errors with debug mode:
running command: GET [my-key]
WRONGTYPE Operation against a key holding the wrong kind of value

This also reduces the number commands ran on Redis from about 4 to 3 per key and should improve performance (unless all of your keys are strings).

I also thought of switching places of PFCOUNT and STRLEN which are ran on string types on the premise that regular strings are more common than HyperLogLog ones and STRLEN being the first conditional could slightly improve performance.

The problem is that STRLEN also works on HLL strings but returns the wrong (or at least not the one we want) value so I left it as is and added a comment for the reasoning behind the order.

### CODE REVIEW

**Comment by oliver006** [comment]
I fixed the CI issue, rebase your branch to pull in the changes from #539, that should  fix the issue.

**Comment by oliver006** [comment]
This PR looks good but would be good to see the tests, etc succeed.

**Comment by kerossin** [comment]
Hey, pulled in your change. Tests are looking good.

**Comment by oliver006** [comment]
Thank you!

**Comment by oliver006** [comment]
Released as v1.26.0
https://github.com/oliver006/redis_exporter/releases/tag/v1.26.0

**Pull request merged**
