### PR TITLE
Update Alpine image to fix security vulnerability

### PR DESCRIPTION
**Pull request by tunguyen9889**

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR!

**Comment by tunguyen9889** [comment]
Thanks @oliver006! May I know when new version will be released?

**Comment by oliver006** [comment]
Give me 10-15 minutes and I'll cut a new release.

**Comment by oliver006** [comment]
Released as [v1.54.0](https://github.com/oliver006/redis_exporter/releases/tag/v1.54.0) - give it 10-15 minutes until the Docker images are build and released.

**Comment by tunguyen9889** [comment]
Thanks much, @oliver006!

**Pull request merged**
