### PR TITLE
Add flag -redis.alias. Allow to give an alias to the redis node(s) address

### PR DESCRIPTION
**Pull request by StephaneBunel**
It could be more friendly (especially in graph) to display the alias than just the node address. Add a modified dashboard for Grafana.

### CODE REVIEW

**Comment by StephaneBunel** [comment]
grafana prometheus redis host alias

**Comment by StephaneBunel** [comment]
Useful when you have multiple Redis instance on the same server.

**Comment by oliver006** [comment]
Thanks for the PR!

I'll be away from my laptop the next couple of days but will try to look at it as soon as I can.

**Comment by oliver006** [comment]
👍

**Comment by vvanholl** [comment]
@StephaneBunel : Good job !

**Pull request merged**
