### PR TITLE
Add output buffer memory usage in client details

### PR DESCRIPTION
**Pull request by ben-tazulev**
- Add output buffer memory usage in client details report

### CODE REVIEW

**Comment by oliver006** [comment]
Hey there, thanks for opening this PR. It's looking pretty good but is still in draft mode. Let me know when you're ready for a review!

**Comment by ben-tazulev** [comment]
> Hey there, thanks for opening this PR. It's looking pretty good but is still in draft mode. Let me know when you're ready for a review!

Hey! Sorry for the delay, I wanted to fix the broken test! :)
I just moved it in review.

**Review by oliver006 — APPROVED** [review]
👍

**Comment by oliver006** [comment]
Thanks for finishing this!

**Pull request merged**
