### PR TITLE
Automatically Multi-target to ARM

### PR DESCRIPTION
**Pull request by HurricanKai**
Simply uses Github Actions to multi-target to arm/arm64/amd64 it's a bit of a mess, but that could be fixed by merging the Commits together

### CODE REVIEW

**Comment by oliver006** [comment]
I don't think I understand what this PR is about, can you explain please?

**Comment by oliver006** [comment]
Builds are currently handled by drone (for docker builds) and the `build-github-binaries.sh` script (for Github binaries) and I have no plans to move to Github Actions.
If there's an interest/need for arm docker containers than it should be done within that context.

**Comment by HurricanKai** [comment]
@oliver006 I don't know how Drone works, but really all that would be need is to set `GOARCH`, and run 3 times, for arm, arm64, and amd64. Would be greatly appreaciated, as this is the only piece of the redis Helm Chart that is missing for simple installation everywhere.

**Comment by oliver006** [comment]
See #312

**Pull request closed without merging**
