### PR TITLE
fix(grafana_prometheus_redis_dashboard): Use alias for instance list

### PR DESCRIPTION
**Pull request by desaintmartin**
Proposition: would that be acceptable?

Of course, if it is acceptable, I would change all queries.

### CODE REVIEW

**Comment by oliver006** [comment]
Why the change from `instance` to `job` ?

**Comment by desaintmartin** [comment]
Using prometheus-operator on a kubernetes cluster with https://github.com/helm/charts/tree/master/stable/redis, "instance" is the Pod IP. Using service or job seems to do the trick, but I wonder if this is the only case where `instance` is the ip.
what are your thoughts on this subject?

**Comment by oliver006** [comment]
That seems to be a problem/use case specific to Kubernetes so I'd rather not make the change to the dashboard.
One possibility would be to have a second json with the Kubernetes version of the dashboard (similar to how there is a 0.3x and 1.x exporter version of the dashboard).

**Comment by naseemkullah** [comment]
Yes please! 

Maybe we can have one json but add instructions to replace `instance` with `job` using `sed`.

**Comment by naseemkullah** [comment]
Actually `job` does not work for me as they are all collected via the `kubernetes-service-endpoints` job.

Perhaps the proper solution is to perform instance relabelling.

**Comment by naseemkullah** [comment]
So I've been playing around with prometheus config and can confirm that instance relabelling works and as per @brian-brazil's advice. 

For example, if the metrics are being scraped via the [pod role](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod), one could add:

```
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: instance ####
            regex: (.*redis.*)
```

as a relabel config to corresponding scrape config.

**Comment by naseemkullah** [comment]
So I've been playing around with prometheus config and can confirm that instance relabelling works as per @brian-brazil's advice.

For example, if the metrics are being scraped via the pod role, one could add:

          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: instance ####
            regex: (.*redis.*)
as a relabel config to corresponding scrape config.

**Comment by naseemkullah** [comment]
So I've been playing around with prometheus config and can confirm that instance relabelling works and as per @brian-brazil's advice.

For example, if the metrics are being scraped via the pod role, one could add:

```
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: instance
            regex: (.*redis.*)
```
as a relabel config to the corresponding scrape config. As per the regex value, only pods with "redis" in their name will be relabelled as such.

**Comment by naseemkullah** [comment]
So I've been playing around with prometheus config and can confirm that instance relabelling works as per @brian-brazil's advice.

For example, if the metrics are being scraped via the pod role, one could add:

```
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: instance
            regex: (.*redis.*)
```
as a relabel config to the corresponding scrape config. As per the regex value, only pods with "redis" in their name will be relabelled as such.

**Comment by oliver006** [comment]
Closing this as there hasn't been any activity in ~2mo.

**Pull request closed without merging**
