### PR TITLE
Add new metrics of info cmd to redis exporter

### PR DESCRIPTION
**Pull request by jjz921024**
#620

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for opening the PR!
Are there any other metrics we can add or just the seven you added?

**Comment by oliver006** [comment]
Thanks for opening the PR!
Are there any other metrics we can add or just the seven you added?

**Comment by jjz921024** [comment]
> Thanks for opening the PR! Are there any other metrics we can add or just the seven you added?

maybe is there a way for users to configure the metrics they're interested in?
It's just an idea, i don't know if it is available.

**Comment by oliver006** [comment]
Eh, don't make anything optional but there are a few more metrics you could add.
Like these for example:
```
io_threads_active
clients_in_timeout_table
number_of_cached_scripts
tracking_total_keys
tracking_total_items
tracking_total_prefixes
total_reads_processed
total_writes_processed
```

**Comment by oliver006** [comment]
Nice work - thanks!

**Pull request merged**
