### PR TITLE
exclude a metric if it contains a dash

### LINKED ISSUE #93: invalid metric name "redis_cluster_stats_messages_auth-ack_received"
howdy, after a bad period on our redis cluster the exporter stopper working as we started seeing:

```
invalid metric name "redis_cluster_stats_messages_auth-ack_received"
```

There's also
```
redis_cluster_stats_messages_auth-req_sent
```

### PR DESCRIPTION
**Pull request by azr**
this fixed #93 for us :)

### CODE REVIEW

**Comment by oliver006** [comment]
That would fix it 👍 

But what about instead changing the metric name and replace the `-` with `_` ?
In that way the metric is still exposed and available to users.

**Comment by oliver006** [comment]
You could replace this line here:
https://github.com/azr/redis_exporter/blob/02859cc0fec36f8d529ccbcb9a16f8456f38d937/exporter/redis.go#L394
with something like 

`metricName := sanitizeMetricName(split[0])`

and 

```
func sanitizeMetricName(n string) {
    // replace "-" with "_" in n 
    // and maybe other characters?
    return n
}
```

**Comment by azr** [comment]
Yup, looks better like this :)

**Comment by azr** [comment]
But that metric is still there

**Comment by oliver006** [comment]
Hmm, no idea why that is.

**Comment by oliver006** [comment]
I just tried to reproduce that but don't see that error on Redis 3.2.8 - what redis version are you using and what's your cluster setup?

**Pull request merged**
