### PR TITLE
change to cross-builder(build on amd64 - run on all)

### PR DESCRIPTION
**Pull request by garrygerber**

### CODE REVIEW

**Comment by garrygerber** [comment]
@oliver006 fixed ARM images, while builder still running on amd64.
Please review :)

**Comment by oliver006** [comment]
Sorry for the delay, couldn't get to this earlier.
Could you explain to me in real simple terms what's currently broken and what this PR fixes?
We always want to build on amd64 (Dockerfile:5), that part makes sense.
The other two changes, is that currently broken and not picking up GOARCH correctly?

**Comment by garrygerber** [comment]
> Sorry for the delay, couldn't get to this earlier. Could you explain to me in real simple terms what's currently broken and what this PR fixes? We always want to build on amd64 (Dockerfile:5), that part makes sense. The other two changes, is that currently broken and not picking up GOARCH correctly?

yes, you are correct, the GOARCH wasn't picked-up correctly and was using the default value which is amd64, and on arm64 it wasn't working obviously

**Comment by oliver006** [comment]
I see, thanks.
Let's try this and I finally got access to docker on ARM so I should be able to test this once I cut a release.

**Comment by oliver006** [comment]
I think this worked!

```
pi @ pi4 ➜  ~  docker run oliver006/redis_exporter
Unable to find image 'oliver006/redis_exporter:latest' locally
latest: Pulling from oliver006/redis_exporter
764d2e53e1a6: Pull complete
b15ebdb3d3ef: Pull complete
b9e85e0ac27f: Pull complete
Digest: sha256:faefa0b378cbb23d5a6ba9afcaae06f59f06544313a59a7b12af0b8b219e586d
Status: Downloaded newer image for oliver006/redis_exporter:latest
time="2021-11-17T12:39:57Z" level=info msg="Redis Metrics Exporter v1.31.4    build date:     sha1: f6e78de9161444a51c8c33fccf223d8d0ae11d4a    Go: go1.17.3    GOOS: linux    GOARCH: arm"
time="2021-11-17T12:39:57Z" level=info msg="Providing metrics at :9121/metrics"
```

**Comment by garrygerber** [comment]
Yes, it worked!!

**Comment by oliver006** [comment]
Thanks for the follow-up fix!!

**Pull request merged**
