### PR TITLE
Add maxmemory_policy and memory reservation metrics

### PR DESCRIPTION
**Pull request by jon-walton**
fixes https://github.com/oliver006/redis_exporter/issues/404
fixes https://github.com/oliver006/redis_exporter/issues/403

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR, this looks really good.
I know we can't test the Azure-specific metrics but could you add a test for the `maxmemory_policy` label somewhere around [here](https://github.com/oliver006/redis_exporter/blob/master/exporter_test.go#L1041-L1070).

**Comment by oliver006** [comment]
Quick bump - @jon-walton did you have a chance to look into adding some tests here? Would love to get this PR merged.

**Comment by jon-walton** [comment]
Apologies, this fell off my radar. I'll try get to it tomorrow

**Comment by jon-walton** [comment]
@oliver006 updated, thanks for the nudge

**Comment by jon-walton** [comment]
also, here's an example of the azure metrics in action

image

from top to bottom

red dash = redis_memory_max_bytes
salmon = redis_memory_max_fragmentation_reservation_bytes
pink/purple = redis_memory_max_reservation_bytes
blue dash = redis_memory_used_peak_bytes
blue = redis_memory_used_bytes

**Comment by oliver006** [comment]
Thanks for adding the tests. And I like the dashboard, looks good!

**Comment by oliver006** [comment]
Released as https://github.com/oliver006/redis_exporter/releases/tag/v1.10.0

**Pull request merged**
