### PR TITLE
Update glide.yaml

### PR DESCRIPTION
**Pull request by 4admin2root**
upgrade redigo to 1.1.0  for rediss://

### CODE REVIEW

**Comment by oliver006** [comment]
Redigo is up to 1.2.0 https://github.com/garyburd/redigo/releases/tag/v1.2.0

Want to bump it to the latest version?

**Comment by oliver006** [comment]
Can you push up an updated version of the glide.yml file using redigo 1.2.0 and then I'll get this merged and cut a new release?

**Comment by 4admin2root** [comment]
done

**Comment by oliver006** [comment]
Thank you!

**Comment by oliver006** [comment]
Thank you!

**Pull request merged**
