### PR TITLE
collect key group metrics asynchronously

### PR DESCRIPTION
**Pull request by avinash-getmega**
This PR helps running the key group extension asynchronously at a defined interval.

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR! I'm a little short with time right now but will try to get to this in the next few days.

**Comment by avinash-getmega** [comment]
> Thanks for the PR! I'm a little short with time right now but will try to get to this in the next few days.

Sure, no problem.

**Comment by oliver006** [comment]
Can you please rebase this PR? 
I'm OOO this week with limited time but will try to look at this closer.
Preferably, the exporter should gather information in real-time and, if you need to, you should control the scrape interval through the Prometheus server. But I understand that can be undesirable.
Have you considered configuring two Prometheus jobs for the same redis instance? One with the regular 15s scrape interval (and no check-keys) and one that scrapes every hour and does the check-key scraping?

**Comment by oliver006** [comment]
Closing this as per last comment, the exporter shouldn't do asyn work when this can be controlled via the Prometheus server config of the target.

**Comment by avinash-getmega** [comment]
> Can you please rebase this PR? I'm OOO this week with limited time but will try to look at this closer. Preferably, the exporter should gather information in real-time and, if you need to, you should control the scrape interval through the Prometheus server. But I understand that can be undesirable. Have you considered configuring two Prometheus jobs for the same redis instance? One with the regular 15s scrape interval (and no check-keys) and one that scrapes every hour and does the check-key scraping?

Yes, this should do the job. Thanks 👍

**Pull request closed without merging**
