### PR TITLE
fix builder to be multi-arch

### PR DESCRIPTION
**Pull request by garrygerber**

### CODE REVIEW

**Comment by oliver006** [comment]
Interesting, let's try this.

@garrygerber - can you rebase your branch please? It has a ton of extra commits from the last PR.

**Comment by garrygerber** [comment]
thanks, @oliver006 for the comment, I've squashed the commits and rebased them, now looks pretty

**Comment by oliver006** [comment]
Great, let's try this.

**Comment by oliver006** [comment]
@garrygerber - that didn't work, both the arm builds failed:
https://cloud.drone.io/oliver006/redis_exporter/1379/1/19
https://cloud.drone.io/oliver006/redis_exporter/1379/1/20

**Pull request merged**
