### PR TITLE
Fix cluster refresh failed  when using pasword file with isCluster mode

### PR DESCRIPTION
**Pull request by chetratep**
This PR is to fix the bug when using password file with `isCluster` mode.

This issue #835

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR, I'll try to review it in the next few days!

**Comment by oliver006** [comment]
I think this makes sense.

Can you please add a test to confirm the expected behavior is working ?

**Comment by chetratep** [comment]
Sure, I'll find sometime later to do it.

**Comment by oliver006** [comment]
Quick bump @chetratep

**Comment by oliver006** [comment]
Thanks for adding the tests @chetratep !

**Pull request merged**
