### PR TITLE
Vendor dependencies

### PR DESCRIPTION
**Pull request by brian-brazil**

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR but I prefer using glide (https://glide.sh/) for vendoring instead of adding 3rd party sources directly to the repo.
Let me see that I can find some time over the next couple of days to get that added.

**Comment by oliver006** [comment]
Closed by #50

**Comment by brian-brazil** [comment]
Thanks, any chance of a release?

**Comment by oliver006** [comment]
Sure thing: https://github.com/oliver006/redis_exporter/releases/tag/v0.10.6

**Comment by brian-brazil** [comment]
Great, thanks

**Pull request closed without merging**
