### PR TITLE
Improve build script

### PR DESCRIPTION
**Pull request by SuperQ**
* Use single gox command to parallelize build.
* Automatically package any archs gox spits out.
* Add sha256sums for packages.

### CODE REVIEW

**Comment by oliver006** [comment]
Nice, this is a lot better than what we got right now.

**Comment by oliver006** [comment]
https://cloud.drone.io/oliver006/redis_exporter/198/1/8

```

GO_LDFLAGS:  -s -w -extldflags "-static" -X main.VERSION=v0.33.0 -X  main.COMMIT_SHA1=09b985767518c57735b7f11b66c15808c4561db4 -X  main.BUILD_DATE=2019-04-09-17:37:28
--
```

:-/

Do the `go build` commands in the build script need the  `-mod=vendor` flag as well?

**Comment by oliver006** [comment]
I guess I could add `-mod=vendor` to the GO_LDFLAGS variable?

**Comment by SuperQ** [comment]
Hrm, I don't know how `gox` passes in those flags. You might need to add `GO111MODULE: on` in the env section of the drone config.

**Comment by oliver006** [comment]
Good suggestion, let me try that.

**Comment by SuperQ** [comment]
It may also need `-mod=vendor` on the GO_LDFLAGS in order to enforce the use of the vendor dir.

**Comment by oliver006** [comment]
Setting the env var seems to have fixed the build, now on to the next issue: 

`rm: cannot remove 'dist/redis_exporter-v0.33.0.windows-386.zip': No such file or directory`

I guess we got to ignore errors here cause for the first zip there's nothing to delete.

**Comment by SuperQ** [comment]
Ahh, yea, `[[ -f $f ]] && rm $f`. Forgot that rm fails on removal of nothing.

**Pull request merged**
